In [1]:
!pip install spotipy

Requirement already satisfied: spotipy in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.26.0)
Requirement already satisfied: redis>=3.5.3 in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from spotipy) (7.4.0)
Requirement already satisfied: requests>=2.25.0 in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from spotipy) (2.32.5)
Requirement already satisfied: urllib3>=1.26.0 in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from spotipy) (2.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.25.0->spotipy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.25.0->spotipy) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.25.0->spotipy) (2026.2.25)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in C:\Users\jason\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.2.2)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import spotipy
from spotipy.oauth2 import SpotifyOAuth
import os
from dotenv import load_dotenv
import pandas as pd

In [4]:
CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI")

In [6]:
sp = spotipy.Spotify(
    auth_manager=SpotifyOAuth(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        redirect_uri=REDIRECT_URI,
        scope="user-read-private"
    )
)

In [7]:
playlist_link = "https://open.spotify.com/playlist/3k4RaZjxSzRIRlrtUEaGka"

In [8]:
playlist_URI = playlist_link.split("/")[-1].split('?')[0]

In [9]:
playlist_URI

'3k4RaZjxSzRIRlrtUEaGka'

In [10]:
data = sp.playlist_tracks(playlist_URI)

In [11]:
data['items']

[{'added_at': '2017-05-20T13:37:28Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22elxmneayyanjgugtzpoavry'},
   'href': 'https://api.spotify.com/v1/users/22elxmneayyanjgugtzpoavry',
   'id': '22elxmneayyanjgugtzpoavry',
   'type': 'user',
   'uri': 'spotify:user:22elxmneayyanjgugtzpoavry'},
  'is_local': False,
  'primary_color': None,
  'item': {'is_playable': True,
   'explicit': False,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'is_playable': True,
    'type': 'album',
    'album_type': 'album',
    'href': 'https://api.spotify.com/v1/albums/33XEF2uGTwEZuVmwXiK9d2',
    'id': '33XEF2uGTwEZuVmwXiK9d2',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b2737da7ca561162d1bdcd603e55',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e027da7ca561162d1bdcd603e55',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d000048517da7ca561162d1bdcd603e55',
      'width': 64}],
    'name': 'All That We Needed',
    'release_date': '2005-01-01',
    'release_date_precision': 'day',
    'uri': 'spotify:album:33XEF2uGTwEZuVmwXiK9d2',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1g1yxsNVPhMUl9GrMjEb2o'},
      'href': 'https://api.spotify.com/v1/artists/1g1yxsNVPhMUl9GrMjEb2o',
      'id': '1g1yxsNVPhMUl9GrMjEb2o',
      'name': "Plain White T's",
      'type': 'artist',
      'uri': 'spotify:artist:1g1yxsNVPhMUl9GrMjEb2o'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/33XEF2uGTwEZuVmwXiK9d2'},
    'total_tracks': 13},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1g1yxsNVPhMUl9GrMjEb2o'},
     'href': 'https://api.spotify.com/v1/artists/1g1yxsNVPhMUl9GrMjEb2o',
     'id': '1g1yxsNVPhMUl9GrMjEb2o',
     'name': "Plain White T's",
     'type': 'artist',
     'uri': 'spotify:artist:1g1yxsNVPhMUl9GrMjEb2o'}],
   'disc_number': 1,
   'track_number': 13,
   'duration_ms': 232533,
   'external_ids': {'isrc': 'US5260507213'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/5O3eNPhckrOCxIBtR5SQLN'},
   'href': 'https://api.spotify.com/v1/tracks/5O3eNPhckrOCxIBtR5SQLN',
   'id': '5O3eNPhckrOCxIBtR5SQLN',
   'name': 'Hey There Delilah',
   'uri': 'spotify:track:5O3eNPhckrOCxIBtR5SQLN',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2017-05-20T13:37:30Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22elxmneayyanjgugtzpoavry'},
   'href': 'https://api.spotify.com/v1/users/22elxmneayyanjgugtzpoavry',
   'id': '22elxmneayyanjgugtzpoavry',
   'type': 'user',
   'uri': 'spotify:user:22elxmneayyanjgugtzpoavry'},
  'is_local': False,
  'primary_color': None,
  'item': {'is_playable': True,
   'explicit': True,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'is_playable': True,
    'type': 'album',
    'album_type': 'album',
    'href': 'https://api.spotify.com/v1/albums/7m7F7SQ3BXvIpvOgjW51Gp',
    'id': '7m7F7SQ3BXvIpvOgjW51Gp',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b273a036e1724bc7f2bab15cfda8',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e02a036e1724bc7f2bab15cfda8',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d00004851a036e1724bc7f2bab15cfda8',
      'width': 64}],
    'name': 'Some Nights',
    'release_date': '2012-02-14',
    'release_date_precision': 'day',
    'uri': 'spotify:album:7m7F7SQ3BXvIpvOgjW51Gp',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5nCi3BB41mBaMH9gfr6Su0'},
      'href': 'https://api.spotify.com/v1/artists/5nCi3BB41mBaMH9gfr6Su0',
      'id': '5nCi3BB41mBaMH9gfr6Su0',
      'name': 'fun.',
      'type': 'artist',
      'uri': 'spotify:artist:5nCi3BB41mBaMH9gfr6Su0'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/7m7F7SQ3BXvIpvOgjW51Gp'},
    'total_tracks': 11},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5nCi3BB41mBaMH9gfr6Su0'},
     'href': 'https://api.spotify.com/v1/artists/5nCi3BB41mBaMH9gfr6Su0',
     'id': '5nCi3BB41mBaMH9gfr6Su0',
     'name': 'fun.',
     'type': 'artist',
     'uri': 'spotify:artist:5nCi3BB41mBaMH9gfr6Su0'}],
   'disc_number': 1,
   'track_number': 2,
   'duration_ms': 277040,
   'external_ids': {'isrc': 'USAT21104050'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/67WTwafOMgegV6ABnBQxcE'},
   'href': 'https://api.spotify.com/v1/tracks/67WTwafOMgegV6ABnBQxcE',
   'id': '67WTwafOMgegV6ABnBQxcE',
   'name': 'Some Nights',
   'uri': 'spotify:track:67WTwafOMgegV6ABnBQxcE',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2017-05-20T13:37:38Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22elxmneayyanjgugtzpoavry'},
   'href': 'https://api.spotify.com/v1/users/22elxmneayyanjgugtzpoavry',
   'id': '22elxmneayyanjgugtzpoavry',
   'type': 'user',
   'uri': 'spotify:user:22elxmneayyanjgugtzpoavry'},
  'is_local': False,
  'primary_color': None,
  'item': {'is_playable': True,
   'explicit': False,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'is_playable': True,
    'type': 'album',
    'album_type': 'single',
    'href': 'https://api.spotify.com/v1/albums/237sMnzUdsdO2GsINgnk2E',
    'id': '237sMnzUdsdO2GsINgnk2E',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b27330b0858b34369e719deaee7e',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e0230b0858b34369e719deaee7e',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d0000485130b0858b34369e719deaee7e',
      'width': 64}],
    'name': "Can't Help Falling In Love",
    'release_date': '2016-02-12',
    'release_date_precision': 'day',
    'uri': 'spotify:album:237sMnzUdsdO2GsINgnk2E',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/40JlNF1w2OiSOyj1nC4y0I'},
      'href': 'https://api.spotify.com/v1/artists/40JlNF1w2OiSOyj1nC4y0I',
      'id': '40JlNF1w2OiSOyj1nC4y0I',
      'name': 'Joseph Vincent',
      'type': 'artist',
      'uri': 'spotify:artist:40JlNF1w2OiSOyj1nC4y0I'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/237sMnzUdsdO2GsINgnk2E'},
    'total_tracks': 1},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/40JlNF1w2OiSOyj1nC4y0I'},
     'href': 'https://api.spotify.com/v1/artists/40JlNF1w2OiSOyj1nC4y0I',
     'id': '40JlNF1w2OiSOyj1nC4y0I',
     'name': 'Joseph Vincent',
     'type': 'artist',
     'uri': 'spotify:artist:40JlNF1w2OiSOyj1nC4y0I'}],
   'disc_number': 1,
   'track_number': 1,
   'duration_ms': 129434,
   'external_ids': {'isrc': 'USE831539252'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/07ceQy7UhpNDA2WhEOJgPp'},
   'href': 'https://api.spotify.com/v1/tracks/07ceQy7UhpNDA2WhEOJgPp',
   'id': '07ceQy7UhpNDA2WhEOJgPp',
   'name': "Can't Help Falling In Love",
   'uri': 'spotify:track:07ceQy7UhpNDA2WhEOJgPp',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2017-05-20T13:37:48Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22elxmneayyanjgugtzpoavry'},
   'href': 'https://api.spotify.com/v1/users/22elxmneayyanjgugtzpoavry',
   'id': '22elxmneayyanjgugtzpoavry',
   'type': 'user',
   'uri': 'spotify:user:22elxmneayyanjgugtzpoavry'},
  'is_local': False,
  'primary_color': None,
  'item': {'is_playable': True,
   'explicit': False,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'is_playable': True,
    'type': 'album',
    'album_type': 'compilation',
    'href': 'https://api.spotify.com/v1/albums/0ZQkueWQFxBrCsfkhxc4jg',
    'id': '0ZQkueWQFxBrCsfkhxc4jg',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b273b84d1ddd2441abba5e3c369c',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e02b84d1ddd2441abba5e3c369c',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d00004851b84d1ddd2441abba5e3c369c',
      'width': 64}],
    'name': 'Begin Again - Music From And Inspired By The Original Motion Picture',
    'release_date': '2014-07-01',
    'release_date_precision': 'day',
    'uri': 'spotify:album:0ZQkueWQFxBrCsfkhxc4jg',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of'},
      'href': 'https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of',
      'id': '0LyfQWJT6nXafLPZqxe9Of',
      'name': 'Various Artists',
      'type': 'artist',
      'uri': 'spotify:artist:0LyfQWJT6nXafLPZqxe9Of'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/0ZQkueWQFxBrCsfkhxc4jg'},
    'total_tracks': 16},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4bYPcJP5jwMhSivRcqie2n'},
     'href': 'https://api.spotify.com/v1/artists/4bYPcJP5jwMhSivRcqie2n',
     'id': '4bYPcJP5jwMhSivRcqie2n',
     'name': 'Adam Levine',
     'type': 'artist',
     'uri': 'spotify:artist:4bYPcJP5jwMhSivRcqie2n'}],
   'disc_number': 1,
   'track_number': 1,
   'duration_ms': 267920,
   'external_ids': {'isrc': 'USUM71406881'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/31UdITPwSCT5LcwbG29G3J'},
   'href': 'https://api.spotify.com/v1/tracks/31UdITPwSCT5LcwbG29G3J',
   'id': '31UdITPwSCT5LcwbG29G3J',
   'name': 'Lost Stars',
   'uri': 'spotify:track:31UdITPwSCT5LcwbG29G3J',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2017-05-20T13:37:52Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22elxmneayyanjgugtzpoavry'},
   'href': 'https://api.spotify.com/v1/users/22elxmneayyanjgugtzpoavry',
   'id': '22elxmneayyanjgugtzpoavry',
   'type': 'user',
   'uri': 'spotify:user:22elxmneayyanjgugtzpoavry'},
  'is_local': False,
  'primary_color': None,
  'item': {'is_playable': True,
   'explicit': False,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'is_playable': True,
    'type': 'album',
    'album_type': 'album',
    'href': 'https://api.spotify.com/v1/albums/7oiJYvEJHsmYtrgviAVIBD',
    'id': '7oiJYvEJHsmYtrgviAVIBD',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b2738d34e1fc21441df43571faaa',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e028d34e1fc21441df43571faaa',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d000048518d34e1fc21441df43571faaa',
      'width': 64}],
    'name': 'Back from the Edge',
    'release_date': '2016-10-28',
    'release_date_precision': 'day',
    'uri': 'spotify:album:7oiJYvEJHsmYtrgviAVIBD',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4IWBUUAFIplrNtaOHcJPRM'},
      'href': 'https://api.spotify.com/v1/artists/4IWBUUAFIplrNtaOHcJPRM',
      'id': '4IWBUUAFIplrNtaOHcJPRM',
      'name': 'James Arthur',
      'type': 'artist',
      'uri': 'spotify:artist:4IWBUUAFIplrNtaOHcJPRM'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/7oiJYvEJHsmYtrgviAVIBD'},
    'total_tracks': 17},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4IWBUUAFIplrNtaOHcJPRM'},
     'href': 'https://api.spotify.com/v1/artists/4IWBUUAFIplrNtaOHcJPRM',
     'id': '4IWBUUAFIplrNtaOHcJPRM',
     'name': 'James Arthur',
     'type': 'artist',
     'uri': 'spotify:artist:4IWBUUAFIplrNtaOHcJPRM'}],
   'disc_number': 1,
   'track_number': 4,
   'duration_ms': 246775,
   'external_ids': {'isrc': 'DEE861600588'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/0VhgEqMTNZwYL1ARDLLNCX'},
   'href': 'https://api.spotify.com/v1/tracks/0VhgEqMTNZwYL1ARDLLNCX',
   'id': '0VhgEqMTNZwYL1ARDLLNCX',
   'name': 'Can I Be Him',
   'uri': 'spotify:track:0VhgEqMTNZwYL1ARDLLNCX',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2017-05-20T13:37:57Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22elxmneayyanjgugtzpoavry'},
   'href': 'https://api.spotify.com/v1/users/22elxmneayyanjgugtzpoavry',
   'id': '22elxmneayyanjgugtzpoavry',
   'type': 'user',
   'uri': 'spotify:user:22elxmneayyanjgugtzpoavry'},
  'is_local': False,
  'primary_color': None,
  'item': {'is_playable': True,
   'explicit': False,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'is_playable': True,
    'type': 'album',
    'album_type': 'compilation',
    'href': 'https://api.spotify.com/v1/albums/2JSHkHdaA87OSnunHO8DRq',
    'id': '2JSHkHdaA87OSnunHO8DRq',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b2734b2b6c6432535e0d76be474c',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e024b2b6c6432535e0d76be474c',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d000048514b2b6c6432535e0d76be474c',
      'width': 64}],
    'name': 'Keep Calm & Stay Cosy',
    'release_date': '2016-03-11',
    'release_date_precision': 'day',
    'uri': 'spotify:album:2JSHkHdaA87OSnunHO8DRq',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of'},
      'href': 'https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of',
      'id': '0LyfQWJT6nXafLPZqxe9Of',
      'name': 'Various Artists',
      'type': 'artist',
      'uri': 'spotify:artist:0LyfQWJT6nXafLPZqxe9Of'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/2JSHkHdaA87OSnunHO8DRq'},
    'total_tracks': 40},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0hEurMDQu99nJRq8pTxO14'},
     'href': 'https://api.spotify.com/v1/artists/0hEurMDQu99nJRq8pTxO14',
     'id': '0hEurMDQu99nJRq8pTxO14',
     'name': 'John Mayer',
     'type': 'artist',
     'uri': 'spotify:artist:0hEurMDQu99nJRq8pTxO14'}],
   'disc_number': 2,
   'track_number': 3,
   'duration_ms': 262973,
   'external_ids': {'isrc': 'USSM10801204'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/4HTqdAfx5jRQuB8ItBifrm'},
   'href': 'https://api.spotify.com/v1/tracks/4HTqdAfx5jRQuB8ItBifrm',
   'id': '4HTqdAfx5jRQuB8ItBifrm',
   'name': "Free Fallin' - Live at the Nokia Theatre, Los Angeles, CA - December 2007",
   'uri': 'spotify:track:4HTqdAfx5jRQuB8ItBifrm',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2017-05-20T13:39:18Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22elxmneayyanjgugtzpoavry'},
   'href': 'https://api.spotify.com/v1/users/22elxmneayyanjgugtzpoavry',
   'id': '22elxmneayyanjgugtzpoavry',
   'type': 'user',
   'uri': 'spotify:user:22elxmneayyanjgugtzpoavry'},
  'is_local': False,
  'primary_color': None,
  'item': {'is_playable': True,
   'explicit': False,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'is_playable': True,
    'type': 'album',
    'album_type': 'album',
    'href': 'https://api.spotify.com/v1/albums/3yHOaiXecTJVUdn7mApZ48',
    'id': '3yHOaiXecTJVUdn7mApZ48',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b2738848d57cbfa7751e028f4dc9',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e028848d57cbfa7751e028f4dc9',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d000048518848d57cbfa7751e028f4dc9',
      'width': 64}],
    'name': 'Room For Squares',
    'release_date': '2001-08-16',
    'release_date_precision': 'day',
    'uri': 'spotify:album:3yHOaiXecTJVUdn7mApZ48',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0hEurMDQu99nJRq8pTxO14'},
      'href': 'https://api.spotify.com/v1/artists/0hEurMDQu99nJRq8pTxO14',
      'id': '0hEurMDQu99nJRq8pTxO14',
      'name': 'John Mayer',
      'type': 'artist',
      'uri': 'spotify:artist:0hEurMDQu99nJRq8pTxO14'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/3yHOaiXecTJVUdn7mApZ48'},
    'total_tracks': 13},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0hEurMDQu99nJRq8pTxO14'},
     'href': 'https://api.spotify.com/v1/artists/0hEurMDQu99nJRq8pTxO14',
     'id': '0hEurMDQu99nJRq8pTxO14',
     'name': 'John Mayer',
     'type': 'artist',
     'uri': 'spotify:artist:0hEurMDQu99nJRq8pTxO14'}],
   'disc_number': 1,
   'track_number': 4,
   'duration_ms': 249626,
   'external_ids': {'isrc': 'USSM10102943'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/7vFv0yFGMJW3qVXbAd9BK9'},
   'href': 'https://api.spotify.com/v1/tracks/7vFv0yFGMJW3qVXbAd9BK9',
   'id': '7vFv0yFGMJW3qVXbAd9BK9',
   'name': 'Your Body Is a Wonderland',
   'uri': 'spotify:track:7vFv0yFGMJW3qVXbAd9BK9',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2017-05-20T13:39:41Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22elxmneayyanjgugtzpoavry'},
   'href': 'https://api.spotify.com/v1/users/22elxmneayyanjgugtzpoavry',
   'id': '22elxmneayyanjgugtzpoavry',
   'type': 'user',
   'uri': 'spotify:user:22elxmneayyanjgugtzpoavry'},
  'is_local': False,
  'primary_color': None,
  'item': {'is_playable': True,
   'explicit': False,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'is_playable': True,
    'type': 'album',
    'album_type': 'compilation',
    'href': 'https://api.spotify.com/v1/albums/1HD7sby4Lr7uGPIQ57tZul',
    'id': '1HD7sby4Lr7uGPIQ57tZul',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b27324877b053a7cfede71174e1a',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e0224877b053a7cfede71174e1a',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d0000485124877b053a7cfede71174e1a',
      'width': 64}],
    'name': "3 Out Of 4 Ain't Bad",
    'release_date': '2010-01-01',
    'release_date_precision': 'day',
    'uri': 'spotify:album:1HD7sby4Lr7uGPIQ57tZul',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'},
      'href': 'https://api.spotify.com/v1/artists/043r4OwwUAYREkBLK5jAiV',
      'id': '043r4OwwUAYREkBLK5jAiV',
      'name': 'FM Static',
      'type': 'artist',
      'uri': 'spotify:artist:043r4OwwUAYREkBLK5jAiV'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/1HD7sby4Lr7uGPIQ57tZul'},
    'total_tracks': 33},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'},
     'href': 'https://api.spotify.com/v1/artists/043r4OwwUAYREkBLK5jAiV',
     'id': '043r4OwwUAYREkBLK5jAiV',
     'name': 'FM Static',
     'type': 'artist',
     'uri': 'spotify:artist:043r4OwwUAYREkBLK5jAiV'}],
   'disc_number': 2,
   'track_number': 4,
   'duration_ms': 213855,
   'external_ids': {'isrc': 'USTN10600092'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/2VR9WymPSvEQo9YyHZrBsC'},
   'href': 'https://api.spotify.com/v1/tracks/2VR9WymPSvEQo9YyHZrBsC',
   'id': '2VR9WymPSvEQo9YyHZrBsC',
   'name': 'The Next Big Thing',
   'uri': 'spotify:track:2VR9WymPSvEQo9YyHZrBsC',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2017-05-20T13:39:45Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22elxmneayyanjgugtzpoavry'},
   'href': 'https://api.spotify.com/v1/users/22elxmneayyanjgugtzpoavry',
   'id': '22elxmneayyanjgugtzpoavry',
   'type': 'user',
   'uri': 'spotify:user:22elxmneayyanjgugtzpoavry'},
  'is_local': False,
  'primary_color': None,
  'item': {'is_playable': True,
   'explicit': False,
   'type': 'track',
   'episode': False,

In [12]:
data['items'][0]['item']['album']

{'is_playable': True,
 'type': 'album',
 'album_type': 'album',
 'href': 'https://api.spotify.com/v1/albums/33XEF2uGTwEZuVmwXiK9d2',
 'id': '33XEF2uGTwEZuVmwXiK9d2',
 'images': [{'height': 640,
   'url': 'https://i.scdn.co/image/ab67616d0000b2737da7ca561162d1bdcd603e55',
   'width': 640},
  {'height': 300,
   'url': 'https://i.scdn.co/image/ab67616d00001e027da7ca561162d1bdcd603e55',
   'width': 300},
  {'height': 64,
   'url': 'https://i.scdn.co/image/ab67616d000048517da7ca561162d1bdcd603e55',
   'width': 64}],
 'name': 'All That We Needed',
 'release_date': '2005-01-01',
 'release_date_precision': 'day',
 'uri': 'spotify:album:33XEF2uGTwEZuVmwXiK9d2',
 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1g1yxsNVPhMUl9GrMjEb2o'},
   'href': 'https://api.spotify.com/v1/artists/1g1yxsNVPhMUl9GrMjEb2o',
   'id': '1g1yxsNVPhMUl9GrMjEb2o',
   'name': "Plain White T's",
   'type': 'artist',
   'uri': 'spotify:artist:1g1yxsNVPhMUl9GrMjEb2o'}],
 'external_urls': {'spotify': 'https://open.spotify.com/album/33XEF2uGTwEZuVmwXiK9d2'},
 'total_tracks': 13}

In [13]:
album_list = []
for row in data['items']:
    album_id = row['item']['album']['id']
    album_name = row['item']['album']['name']
    album_release_date = row['item']['album']['release_date']
    album_total_tracks = row['item']['album']['total_tracks']
    album_url = row['item']['album']['external_urls']
    album_element = {'album_id' : album_id, 'album_name' : album_name, 'album_release_date' : album_release_date, 'album_total_tracks' : album_total_tracks, 'album_url' : album_url}
    album_list.append(album_element)

In [14]:
album_list

[{'album_id': '33XEF2uGTwEZuVmwXiK9d2',
  'album_name': 'All That We Needed',
  'album_release_date': '2005-01-01',
  'album_total_tracks': 13,
  'album_url': {'spotify': 'https://open.spotify.com/album/33XEF2uGTwEZuVmwXiK9d2'}},
 {'album_id': '7m7F7SQ3BXvIpvOgjW51Gp',
  'album_name': 'Some Nights',
  'album_release_date': '2012-02-14',
  'album_total_tracks': 11,
  'album_url': {'spotify': 'https://open.spotify.com/album/7m7F7SQ3BXvIpvOgjW51Gp'}},
 {'album_id': '237sMnzUdsdO2GsINgnk2E',
  'album_name': "Can't Help Falling In Love",
  'album_release_date': '2016-02-12',
  'album_total_tracks': 1,
  'album_url': {'spotify': 'https://open.spotify.com/album/237sMnzUdsdO2GsINgnk2E'}},
 {'album_id': '0ZQkueWQFxBrCsfkhxc4jg',
  'album_name': 'Begin Again - Music From And Inspired By The Original Motion Picture',
  'album_release_date': '2014-07-01',
  'album_total_tracks': 16,
  'album_url': {'spotify': 'https://open.spotify.com/album/0ZQkueWQFxBrCsfkhxc4jg'}},
 {'album_id': '7oiJYvEJHsmYtrgviAVIBD',
  'album_name': 'Back from the Edge',
  'album_release_date': '2016-10-28',
  'album_total_tracks': 17,
  'album_url': {'spotify': 'https://open.spotify.com/album/7oiJYvEJHsmYtrgviAVIBD'}},
 {'album_id': '2JSHkHdaA87OSnunHO8DRq',
  'album_name': 'Keep Calm & Stay Cosy',
  'album_release_date': '2016-03-11',
  'album_total_tracks': 40,
  'album_url': {'spotify': 'https://open.spotify.com/album/2JSHkHdaA87OSnunHO8DRq'}},
 {'album_id': '3yHOaiXecTJVUdn7mApZ48',
  'album_name': 'Room For Squares',
  'album_release_date': '2001-08-16',
  'album_total_tracks': 13,
  'album_url': {'spotify': 'https://open.spotify.com/album/3yHOaiXecTJVUdn7mApZ48'}},
 {'album_id': '1HD7sby4Lr7uGPIQ57tZul',
  'album_name': "3 Out Of 4 Ain't Bad",
  'album_release_date': '2010-01-01',
  'album_total_tracks': 33,
  'album_url': {'spotify': 'https://open.spotify.com/album/1HD7sby4Lr7uGPIQ57tZul'}},
 {'album_id': '2yuA6JcakppoD7xbiJmOix',
  'album_name': 'Critically Ashamed',
  'album_release_date': '2006-01-01',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/2yuA6JcakppoD7xbiJmOix'}},
 {'album_id': '2yuA6JcakppoD7xbiJmOix',
  'album_name': 'Critically Ashamed',
  'album_release_date': '2006-01-01',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/2yuA6JcakppoD7xbiJmOix'}},
 {'album_id': '2yuA6JcakppoD7xbiJmOix',
  'album_name': 'Critically Ashamed',
  'album_release_date': '2006-01-01',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/2yuA6JcakppoD7xbiJmOix'}},
 {'album_id': '2yuA6JcakppoD7xbiJmOix',
  'album_name': 'Critically Ashamed',
  'album_release_date': '2006-01-01',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/2yuA6JcakppoD7xbiJmOix'}},
 {'album_id': '2yuA6JcakppoD7xbiJmOix',
  'album_name': 'Critically Ashamed',
  'album_release_date': '2006-01-01',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/2yuA6JcakppoD7xbiJmOix'}},
 {'album_id': '2yuA6JcakppoD7xbiJmOix',
  'album_name': 'Critically Ashamed',
  'album_release_date': '2006-01-01',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/2yuA6JcakppoD7xbiJmOix'}},
 {'album_id': '5hQQ9xmWchSRYXNI6gJhz6',
  'album_name': 'Dear Diary',
  'album_release_date': '2009-01-01',
  'album_total_tracks': 10,
  'album_url': {'spotify': 'https://open.spotify.com/album/5hQQ9xmWchSRYXNI6gJhz6'}},
 {'album_id': '2yuA6JcakppoD7xbiJmOix',
  'album_name': 'Critically Ashamed',
  'album_release_date': '2006-01-01',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/2yuA6JcakppoD7xbiJmOix'}},
 {'album_id': '2yuA6JcakppoD7xbiJmOix',
  'album_name': 'Critically Ashamed',
  'album_release_date': '2006-01-01',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/2yuA6JcakppoD7xbiJmOix'}},
 {'album_id': '6TyPSzd5rA2rQ9yLJJ1Gg2',
  'album_name': "Don't You Fake It",
  'album_release_date': '2006-01-01',
  'album_total_tracks': 11,
  'album_url': {'spotify': 'https://open.spotify.com/album/6TyPSzd5rA2rQ9yLJJ1Gg2'}},
 {'album_id': '6TyPSzd5rA2rQ9yLJJ1Gg2',
  'album_name': "Don't You Fake It",
  'album_release_date': '2006-01-01',
  'album_total_tracks': 11,
  'album_url': {'spotify': 'https://open.spotify.com/album/6TyPSzd5rA2rQ9yLJJ1Gg2'}},
 {'album_id': '6TyPSzd5rA2rQ9yLJJ1Gg2',
  'album_name': "Don't You Fake It",
  'album_release_date': '2006-01-01',
  'album_total_tracks': 11,
  'album_url': {'spotify': 'https://open.spotify.com/album/6TyPSzd5rA2rQ9yLJJ1Gg2'}},
 {'album_id': '6WZXOQ3wVanWKocZND5qoZ',
  'album_name': 'Sunshine State of Mind',
  'album_release_date': '2011-01-01',
  'album_total_tracks': 11,
  'album_url': {'spotify': 'https://open.spotify.com/album/6WZXOQ3wVanWKocZND5qoZ'}},
 {'album_id': '5kykHij9W4lQ4fFEfIo7BB',
  'album_name': 'We The Kings',
  'album_release_date': '2007-10-07',
  'album_total_tracks': 11,
  'album_url': {'spotify': 'https://open.spotify.com/album/5kykHij9W4lQ4fFEfIo7BB'}},
 {'album_id': '6SdmyV1DoEIWU6HDal5BgY',
  'album_name': 'Future Hearts',
  'album_release_date': '2015-04-07',
  'album_total_tracks': 13,
  'album_url': {'spotify': 'https://open.spotify.com/album/6SdmyV1DoEIWU6HDal5BgY'}},
 {'album_id': '7GcuimRczCCOblhJr0NgzD',
  'album_name': "So Wrong, It's Right",
  'album_release_date': '2007-09-25',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/7GcuimRczCCOblhJr0NgzD'}},
 {'album_id': '3bex1JTyWnMeQDX5kodWtc',
  'album_name': 'Symphony Soldier',
  'album_release_date': '2011',
  'album_total_tracks': 14,
  'album_url': {'spotify': 'https://open.spotify.com/album/3bex1JTyWnMeQDX5kodWtc'}},
 {'album_id': '3bex1JTyWnMeQDX5kodWtc',
  'album_name': 'Symphony Soldier',
  'album_release_date': '2011',
  'album_total_tracks': 14,
  'album_url': {'spotify': 'https://open.spotify.com/album/3bex1JTyWnMeQDX5kodWtc'}},
 {'album_id': '0mtf5Q6b4CD0mx7UTtL0l1',
  'album_name': 'Lock Me Up',
  'album_release_date': '2014-01-01',
  'album_total_tracks': 5,
  'album_url': {'spotify': 'https://open.spotify.com/album/0mtf5Q6b4CD0mx7UTtL0l1'}},
 {'album_id': '3bex1JTyWnMeQDX5kodWtc',
  'album_name': 'Symphony Soldier',
  'album_release_date': '2011',
  'album_total_tracks': 14,
  'album_url': {'spotify': 'https://open.spotify.com/album/3bex1JTyWnMeQDX5kodWtc'}},
 {'album_id': '3bex1JTyWnMeQDX5kodWtc',
  'album_name': 'Symphony Soldier',
  'album_release_date': '2011',
  'album_total_tracks': 14,
  'album_url': {'spotify': 'https://open.spotify.com/album/3bex1JTyWnMeQDX5kodWtc'}},
 {'album_id': '3bex1JTyWnMeQDX5kodWtc',
  'album_name': 'Symphony Soldier',
  'album_release_date': '2011',
  'album_total_tracks': 14,
  'album_url': {'spotify': 'https://open.spotify.com/album/3bex1JTyWnMeQDX5kodWtc'}},
 {'album_id': '6RSpKXfvVzCqtLi6VySxsU',
  'album_name': 'Still Not Getting Any...',
  'album_release_date': '2004-10-25',
  'album_total_tracks': 13,
  'album_url': {'spotify': 'https://open.spotify.com/album/6RSpKXfvVzCqtLi6VySxsU'}},
 {'album_id': '1vD9N1kYJtYEBEzV1KZpH0',
  'album_name': 'The Love Album',
  'album_release_date': '2006-11-17',
  'album_total_tracks': 17,
  'album_url': {'spotify': 'https://open.spotify.com/album/1vD9N1kYJtYEBEzV1KZpH0'}},
 {'album_id': '3Iq8rXgxwlSPpRsIacNLgK',
  'album_name': 'Greatest Hits',
  'album_release_date': '2011-11-21',
  'album_total_tracks': 18,
  'album_url': {'spotify': 'https://open.spotify.com/album/3Iq8rXgxwlSPpRsIacNLgK'}},
 {'album_id': '1tjE6cuUdnscgwxTt49ouH',
  'album_name': 'Simple Plan',
  'album_release_date': '2008-02-06',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/1tjE6cuUdnscgwxTt49ouH'}},
 {'album_id': '0cDtMoDHC3Pja0V1qrfBdT',
  'album_name': 'Taking One for the Team',
  'album_release_date': '2016-02-19',
  'album_total_tracks': 14,
  'album_url': {'spotify': 'https://open.spotify.com/album/0cDtMoDHC3Pja0V1qrfBdT'}},
 {'album_id': '3rEl0zv6lbVZiB79uHAQ5y',
  'album_name': 'No Pads, No Helmets...Just Balls',
  'album_release_date': '2002-03-19',
  'album_total_tracks': 13,
  'album_url': {'spotify': 'https://open.spotify.com/album/3rEl0zv6lbVZiB79uHAQ5y'}},
 {'album_id': '7oiJYvEJHsmYtrgviAVIBD',
  'album_name': 'Back from the Edge',
  'album_release_date': '2016-10-28',
  'album_total_tracks': 17,
  'album_url': {'spotify': 'https://open.spotify.com/album/7oiJYvEJHsmYtrgviAVIBD'}},
 {'album_id': '0MeOIA0wwSa6nW79jy8QcZ',
  'album_name': 'x (Wembley Edition)',
  'album_release_date': '2015-11-13',
  'album_total_tracks': 23,
  'album_url': {'spotify': 'https://open.spotify.com/album/0MeOIA0wwSa6nW79jy8QcZ'}},
 {'album_id': '1CEODgTmTwLyabvwd7HBty',
  'album_name': 'Viva La Vida or Death and All His Friends',
  'album_release_date': '2008-06-06',
  'album_total_tracks': 10,
  'album_url': {'spotify': 'https://open.spotify.com/album/1CEODgTmTwLyabvwd7HBty'}},
 {'album_id': '3cfAM8b8KqJRoIzt3zLKqw',
  'album_name': 'A Head Full of Dreams',
  'album_release_date': '2015-12-04',
  'album_total_tracks': 11,
  'album_url': {'spotify': 'https://open.spotify.com/album/3cfAM8b8KqJRoIzt3zLKqw'}},
 {'album_id': '2G4AUqfwxcV1UdQjm2ouYr',
  'album_name': 'Ghost Stories',
  'album_release_date': '2014-05-16',
  'album_total_tracks': 9,
  'album_url': {'spotify': 'https://open.spotify.com/album/2G4AUqfwxcV1UdQjm2ouYr'}},
 {'album_id': '0RHX9XECH8IVI3LNgWDpmQ',
  'album_name': 'A Rush of Blood to the Head',
  'album_release_date': '2002-08-27',
  'album_total_tracks': 11,
  'album_url': {'spotify': 'https://open.spotify.com/album/0RHX9XECH8IVI3LNgWDpmQ'}},
 {'album_id': '0wvQovgaVU99eqw8n3g22S',
  'album_name': 'Backstreet Boys',
  'album_release_date': '1996',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/0wvQovgaVU99eqw8n3g22S'}},
 {'album_id': '1NslKOZobWxINFaFkLol3r',
  'album_name': 'The Hits--Chapter One',
  'album_release_date': '2001-10-23',
  'album_total_tracks': 13,
  'album_url': {'spotify': 'https://open.spotify.com/album/1NslKOZobWxINFaFkLol3r'}},
 {'album_id': '0UccZZgelTAbbk3OSPZymO',
  'album_name': 'Greatest Hits Volume One - The Singles',
  'album_release_date': '2007-11-06',
  'album_total_tracks': 14,
  'album_url': {'spotify': 'https://open.spotify.com/album/0UccZZgelTAbbk3OSPZymO'}},
 {'album_id': '1VKNHcrUppE8i5oAhg4o6k',
  'album_name': 'No Name Face',
  'album_release_date': '2000',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/1VKNHcrUppE8i5oAhg4o6k'}},
 {'album_id': '3wJfFDP79V0vuGaAasTIz6',
  'album_name': 'Lifehouse',
  'album_release_date': '2005-01-01',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/3wJfFDP79V0vuGaAasTIz6'}},
 {'album_id': '3ibdlhMmbFPMYoWvwHCzI3',
  'album_name': 'The Fray',
  'album_release_date': '2009-02-02',
  'album_total_tracks': 10,
  'album_url': {'spotify': 'https://open.spotify.com/album/3ibdlhMmbFPMYoWvwHCzI3'}},
 {'album_id': '1IM3GwptCGYjRkzCBolyFK',
  'album_name': 'How To Save A Life',
  'album_release_date': '2005-09-13',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/1IM3GwptCGYjRkzCBolyFK'}},
 {'album_id': '3mNoFlD1wsoXfkljfFzExT',
  'album_name': 'TALKING IS HARD',
  'album_release_date': '2014-12-02',
  'album_total_tracks': 12,
  'album_url': {'spotify': 'https://open.spotify.com/album/3mNoFlD1wsoXfkljfFzExT'}}]

In [16]:
data['items'][0]['item']['artists']

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/1g1yxsNVPhMUl9GrMjEb2o'},
  'href': 'https://api.spotify.com/v1/artists/1g1yxsNVPhMUl9GrMjEb2o',
  'id': '1g1yxsNVPhMUl9GrMjEb2o',
  'name': "Plain White T's",
  'type': 'artist',
  'uri': 'spotify:artist:1g1yxsNVPhMUl9GrMjEb2o'}]

In [21]:
data['items'][0]['item']['artists'][0]

{'external_urls': {'spotify': 'https://open.spotify.com/artist/1g1yxsNVPhMUl9GrMjEb2o'},
 'href': 'https://api.spotify.com/v1/artists/1g1yxsNVPhMUl9GrMjEb2o',
 'id': '1g1yxsNVPhMUl9GrMjEb2o',
 'name': "Plain White T's",
 'type': 'artist',
 'uri': 'spotify:artist:1g1yxsNVPhMUl9GrMjEb2o'}

In [22]:
artist_list = []
for row in data['items']:
    artist_id = row['item']['artists'][0]['id']
    artist_name = row['item']['artists'][0]['name']
    artist_url = row['item']['artists'][0]['external_urls']
    artist_element = {'artist_id' : artist_id, 'artist_name' : artist_name, 'artist_url' : artist_url}
    artist_list.append(artist_element)

In [24]:
artist_list

[{'artist_id': '1g1yxsNVPhMUl9GrMjEb2o',
  'artist_name': "Plain White T's",
  'artist_url': {'spotify': 'https://open.spotify.com/artist/1g1yxsNVPhMUl9GrMjEb2o'}},
 {'artist_id': '5nCi3BB41mBaMH9gfr6Su0',
  'artist_name': 'fun.',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/5nCi3BB41mBaMH9gfr6Su0'}},
 {'artist_id': '40JlNF1w2OiSOyj1nC4y0I',
  'artist_name': 'Joseph Vincent',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/40JlNF1w2OiSOyj1nC4y0I'}},
 {'artist_id': '4bYPcJP5jwMhSivRcqie2n',
  'artist_name': 'Adam Levine',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/4bYPcJP5jwMhSivRcqie2n'}},
 {'artist_id': '4IWBUUAFIplrNtaOHcJPRM',
  'artist_name': 'James Arthur',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/4IWBUUAFIplrNtaOHcJPRM'}},
 {'artist_id': '0hEurMDQu99nJRq8pTxO14',
  'artist_name': 'John Mayer',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/0hEurMDQu99nJRq8pTxO14'}},
 {'artist_id': '0hEurMDQu99nJRq8pTxO14',
  'artist_name': 'John Mayer',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/0hEurMDQu99nJRq8pTxO14'}},
 {'artist_id': '043r4OwwUAYREkBLK5jAiV',
  'artist_name': 'FM Static',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'}},
 {'artist_id': '043r4OwwUAYREkBLK5jAiV',
  'artist_name': 'FM Static',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'}},
 {'artist_id': '043r4OwwUAYREkBLK5jAiV',
  'artist_name': 'FM Static',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'}},
 {'artist_id': '043r4OwwUAYREkBLK5jAiV',
  'artist_name': 'FM Static',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'}},
 {'artist_id': '043r4OwwUAYREkBLK5jAiV',
  'artist_name': 'FM Static',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'}},
 {'artist_id': '043r4OwwUAYREkBLK5jAiV',
  'artist_name': 'FM Static',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'}},
 {'artist_id': '043r4OwwUAYREkBLK5jAiV',
  'artist_name': 'FM Static',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'}},
 {'artist_id': '043r4OwwUAYREkBLK5jAiV',
  'artist_name': 'FM Static',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'}},
 {'artist_id': '043r4OwwUAYREkBLK5jAiV',
  'artist_name': 'FM Static',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'}},
 {'artist_id': '043r4OwwUAYREkBLK5jAiV',
  'artist_name': 'FM Static',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/043r4OwwUAYREkBLK5jAiV'}},
 {'artist_id': '1SImpQO0GbjRgvlwCcCtFo',
  'artist_name': 'The Red Jumpsuit Apparatus',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/1SImpQO0GbjRgvlwCcCtFo'}},
 {'artist_id': '1SImpQO0GbjRgvlwCcCtFo',
  'artist_name': 'The Red Jumpsuit Apparatus',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/1SImpQO0GbjRgvlwCcCtFo'}},
 {'artist_id': '1SImpQO0GbjRgvlwCcCtFo',
  'artist_name': 'The Red Jumpsuit Apparatus',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/1SImpQO0GbjRgvlwCcCtFo'}},
 {'artist_id': '3ao3jf5d70Tf4fPh2bnXVl',
  'artist_name': 'We The Kings',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/3ao3jf5d70Tf4fPh2bnXVl'}},
 {'artist_id': '3ao3jf5d70Tf4fPh2bnXVl',
  'artist_name': 'We The Kings',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/3ao3jf5d70Tf4fPh2bnXVl'}},
 {'artist_id': '46gyXjRIvN1NL1eCB8GBxo',
  'artist_name': 'All Time Low',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/46gyXjRIvN1NL1eCB8GBxo'}},
 {'artist_id': '46gyXjRIvN1NL1eCB8GBxo',
  'artist_name': 'All Time Low',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/46gyXjRIvN1NL1eCB8GBxo'}},
 {'artist_id': '2C2sVVXanbOpymYBMpsi89',
  'artist_name': 'The Cab',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/2C2sVVXanbOpymYBMpsi89'}},
 {'artist_id': '2C2sVVXanbOpymYBMpsi89',
  'artist_name': 'The Cab',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/2C2sVVXanbOpymYBMpsi89'}},
 {'artist_id': '2C2sVVXanbOpymYBMpsi89',
  'artist_name': 'The Cab',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/2C2sVVXanbOpymYBMpsi89'}},
 {'artist_id': '2C2sVVXanbOpymYBMpsi89',
  'artist_name': 'The Cab',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/2C2sVVXanbOpymYBMpsi89'}},
 {'artist_id': '2C2sVVXanbOpymYBMpsi89',
  'artist_name': 'The Cab',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/2C2sVVXanbOpymYBMpsi89'}},
 {'artist_id': '2C2sVVXanbOpymYBMpsi89',
  'artist_name': 'The Cab',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/2C2sVVXanbOpymYBMpsi89'}},
 {'artist_id': '2p4FqHnazRucYQHyDCdBrJ',
  'artist_name': 'Simple Plan',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/2p4FqHnazRucYQHyDCdBrJ'}},
 {'artist_id': '5Z1CCuBsyhEHngq3U5IraY',
  'artist_name': 'Westlife',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/5Z1CCuBsyhEHngq3U5IraY'}},
 {'artist_id': '5Z1CCuBsyhEHngq3U5IraY',
  'artist_name': 'Westlife',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/5Z1CCuBsyhEHngq3U5IraY'}},
 {'artist_id': '2p4FqHnazRucYQHyDCdBrJ',
  'artist_name': 'Simple Plan',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/2p4FqHnazRucYQHyDCdBrJ'}},
 {'artist_id': '2p4FqHnazRucYQHyDCdBrJ',
  'artist_name': 'Simple Plan',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/2p4FqHnazRucYQHyDCdBrJ'}},
 {'artist_id': '2p4FqHnazRucYQHyDCdBrJ',
  'artist_name': 'Simple Plan',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/2p4FqHnazRucYQHyDCdBrJ'}},
 {'artist_id': '4IWBUUAFIplrNtaOHcJPRM',
  'artist_name': 'James Arthur',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/4IWBUUAFIplrNtaOHcJPRM'}},
 {'artist_id': '6eUKZXaKkcviH0Ku9w2n3V',
  'artist_name': 'Ed Sheeran',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'}},
 {'artist_id': '4gzpq5DPGxSnKTe4SA8HAU',
  'artist_name': 'Coldplay',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU'}},
 {'artist_id': '4gzpq5DPGxSnKTe4SA8HAU',
  'artist_name': 'Coldplay',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU'}},
 {'artist_id': '4gzpq5DPGxSnKTe4SA8HAU',
  'artist_name': 'Coldplay',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU'}},
 {'artist_id': '4gzpq5DPGxSnKTe4SA8HAU',
  'artist_name': 'Coldplay',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU'}},
 {'artist_id': '5rSXSAkZ67PYJSvpUpkOr7',
  'artist_name': 'Backstreet Boys',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/5rSXSAkZ67PYJSvpUpkOr7'}},
 {'artist_id': '5rSXSAkZ67PYJSvpUpkOr7',
  'artist_name': 'Backstreet Boys',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/5rSXSAkZ67PYJSvpUpkOr7'}},
 {'artist_id': '2sil8z5kiy4r76CRTXxBCA',
  'artist_name': 'The Goo Goo Dolls',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/2sil8z5kiy4r76CRTXxBCA'}},
 {'artist_id': '5PokPZn11xzZXyXSfnvIM3',
  'artist_name': 'Lifehouse',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/5PokPZn11xzZXyXSfnvIM3'}},
 {'artist_id': '5PokPZn11xzZXyXSfnvIM3',
  'artist_name': 'Lifehouse',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/5PokPZn11xzZXyXSfnvIM3'}},
 {'artist_id': '0zOcE3mg9nS6l3yxt1Y0bK',
  'artist_name': 'The Fray',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/0zOcE3mg9nS6l3yxt1Y0bK'}},
 {'artist_id': '0zOcE3mg9nS6l3yxt1Y0bK',
  'artist_name': 'The Fray',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/0zOcE3mg9nS6l3yxt1Y0bK'}},
 {'artist_id': '6DIS6PRrLS3wbnZsf7vYic',
  'artist_name': 'WALK THE MOON',
  'artist_url': {'spotify': 'https://open.spotify.com/artist/6DIS6PRrLS3wbnZsf7vYic'}}]

In [37]:
data['items'][0]

{'added_at': '2017-05-20T13:37:28Z',
 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/22elxmneayyanjgugtzpoavry'},
  'href': 'https://api.spotify.com/v1/users/22elxmneayyanjgugtzpoavry',
  'id': '22elxmneayyanjgugtzpoavry',
  'type': 'user',
  'uri': 'spotify:user:22elxmneayyanjgugtzpoavry'},
 'is_local': False,
 'primary_color': None,
 'item': {'is_playable': True,
  'explicit': False,
  'type': 'track',
  'episode': False,
  'track': True,
  'album': {'is_playable': True,
   'type': 'album',
   'album_type': 'album',
   'href': 'https://api.spotify.com/v1/albums/33XEF2uGTwEZuVmwXiK9d2',
   'id': '33XEF2uGTwEZuVmwXiK9d2',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b2737da7ca561162d1bdcd603e55',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e027da7ca561162d1bdcd603e55',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d000048517da7ca561162d1bdcd603e55',
     'width': 64}],
   'name': 'All That We Needed',
   'release_date': '2005-01-01',
   'release_date_precision': 'day',
   'uri': 'spotify:album:33XEF2uGTwEZuVmwXiK9d2',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1g1yxsNVPhMUl9GrMjEb2o'},
     'href': 'https://api.spotify.com/v1/artists/1g1yxsNVPhMUl9GrMjEb2o',
     'id': '1g1yxsNVPhMUl9GrMjEb2o',
     'name': "Plain White T's",
     'type': 'artist',
     'uri': 'spotify:artist:1g1yxsNVPhMUl9GrMjEb2o'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/33XEF2uGTwEZuVmwXiK9d2'},
   'total_tracks': 13},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1g1yxsNVPhMUl9GrMjEb2o'},
    'href': 'https://api.spotify.com/v1/artists/1g1yxsNVPhMUl9GrMjEb2o',
    'id': '1g1yxsNVPhMUl9GrMjEb2o',
    'name': "Plain White T's",
    'type': 'artist',
    'uri': 'spotify:artist:1g1yxsNVPhMUl9GrMjEb2o'}],
  'disc_number': 1,
  'track_number': 13,
  'duration_ms': 232533,
  'external_ids': {'isrc': 'US5260507213'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/5O3eNPhckrOCxIBtR5SQLN'},
  'href': 'https://api.spotify.com/v1/tracks/5O3eNPhckrOCxIBtR5SQLN',
  'id': '5O3eNPhckrOCxIBtR5SQLN',
  'name': 'Hey There Delilah',
  'uri': 'spotify:track:5O3eNPhckrOCxIBtR5SQLN',
  'is_local': False},
 'video_thumbnail': {'url': None}}

In [35]:
song_list = []
for row in data['items']:
    song_id = row['item']['id']
    song_name = row['item']['name']
    song_duration = row['item']['duration_ms']
    song_url = row['item']['external_urls']['spotify']
    song_added = row['added_at']
    album_id = row['item']['album']['id']
    artist_id = row['item']['artists'][0]['id']
    song_element = {'song_id' : song_id, 
                    'song_name' : song_name, 
                    'song_duration' : song_duration, 
                    'song_url' : song_url,
                   'song_added' : song_added,
                   'album_id' : album_id,
                   'artist_id' : artist_id}
    song_list.append(song_element)

In [36]:
song_list

[{'song_id': '5O3eNPhckrOCxIBtR5SQLN',
  'song_name': 'Hey There Delilah',
  'song_duration': 232533,
  'song_url': 'https://open.spotify.com/track/5O3eNPhckrOCxIBtR5SQLN',
  'song_added': '2017-05-20T13:37:28Z',
  'album_id': '33XEF2uGTwEZuVmwXiK9d2',
  'artist_id': '1g1yxsNVPhMUl9GrMjEb2o'},
 {'song_id': '67WTwafOMgegV6ABnBQxcE',
  'song_name': 'Some Nights',
  'song_duration': 277040,
  'song_url': 'https://open.spotify.com/track/67WTwafOMgegV6ABnBQxcE',
  'song_added': '2017-05-20T13:37:30Z',
  'album_id': '7m7F7SQ3BXvIpvOgjW51Gp',
  'artist_id': '5nCi3BB41mBaMH9gfr6Su0'},
 {'song_id': '07ceQy7UhpNDA2WhEOJgPp',
  'song_name': "Can't Help Falling In Love",
  'song_duration': 129434,
  'song_url': 'https://open.spotify.com/track/07ceQy7UhpNDA2WhEOJgPp',
  'song_added': '2017-05-20T13:37:38Z',
  'album_id': '237sMnzUdsdO2GsINgnk2E',
  'artist_id': '40JlNF1w2OiSOyj1nC4y0I'},
 {'song_id': '31UdITPwSCT5LcwbG29G3J',
  'song_name': 'Lost Stars',
  'song_duration': 267920,
  'song_url': 'https://open.spotify.com/track/31UdITPwSCT5LcwbG29G3J',
  'song_added': '2017-05-20T13:37:48Z',
  'album_id': '0ZQkueWQFxBrCsfkhxc4jg',
  'artist_id': '4bYPcJP5jwMhSivRcqie2n'},
 {'song_id': '0VhgEqMTNZwYL1ARDLLNCX',
  'song_name': 'Can I Be Him',
  'song_duration': 246775,
  'song_url': 'https://open.spotify.com/track/0VhgEqMTNZwYL1ARDLLNCX',
  'song_added': '2017-05-20T13:37:52Z',
  'album_id': '7oiJYvEJHsmYtrgviAVIBD',
  'artist_id': '4IWBUUAFIplrNtaOHcJPRM'},
 {'song_id': '4HTqdAfx5jRQuB8ItBifrm',
  'song_name': "Free Fallin' - Live at the Nokia Theatre, Los Angeles, CA - December 2007",
  'song_duration': 262973,
  'song_url': 'https://open.spotify.com/track/4HTqdAfx5jRQuB8ItBifrm',
  'song_added': '2017-05-20T13:37:57Z',
  'album_id': '2JSHkHdaA87OSnunHO8DRq',
  'artist_id': '0hEurMDQu99nJRq8pTxO14'},
 {'song_id': '7vFv0yFGMJW3qVXbAd9BK9',
  'song_name': 'Your Body Is a Wonderland',
  'song_duration': 249626,
  'song_url': 'https://open.spotify.com/track/7vFv0yFGMJW3qVXbAd9BK9',
  'song_added': '2017-05-20T13:39:18Z',
  'album_id': '3yHOaiXecTJVUdn7mApZ48',
  'artist_id': '0hEurMDQu99nJRq8pTxO14'},
 {'song_id': '2VR9WymPSvEQo9YyHZrBsC',
  'song_name': 'The Next Big Thing',
  'song_duration': 213855,
  'song_url': 'https://open.spotify.com/track/2VR9WymPSvEQo9YyHZrBsC',
  'song_added': '2017-05-20T13:39:41Z',
  'album_id': '1HD7sby4Lr7uGPIQ57tZul',
  'artist_id': '043r4OwwUAYREkBLK5jAiV'},
 {'song_id': '40y2rT0VfBq1otRh3MFJID',
  'song_name': 'Waste Of Time',
  'song_duration': 170093,
  'song_url': 'https://open.spotify.com/track/40y2rT0VfBq1otRh3MFJID',
  'song_added': '2017-05-20T13:39:45Z',
  'album_id': '2yuA6JcakppoD7xbiJmOix',
  'artist_id': '043r4OwwUAYREkBLK5jAiV'},
 {'song_id': '3lGH1F1fPqi62wozujGLX3',
  'song_name': 'Girl Of The Year',
  'song_duration': 184240,
  'song_url': 'https://open.spotify.com/track/3lGH1F1fPqi62wozujGLX3',
  'song_added': '2017-05-20T13:39:48Z',
  'album_id': '2yuA6JcakppoD7xbiJmOix',
  'artist_id': '043r4OwwUAYREkBLK5jAiV'},
 {'song_id': '1MNrz4xpmdsVtEAKjFfGy9',
  'song_name': "America's Next Freak",
  'song_duration': 210960,
  'song_url': 'https://open.spotify.com/track/1MNrz4xpmdsVtEAKjFfGy9',
  'song_added': '2017-05-20T13:39:52Z',
  'album_id': '2yuA6JcakppoD7xbiJmOix',
  'artist_id': '043r4OwwUAYREkBLK5jAiV'},
 {'song_id': '36GiaCkptseXOnP1SgG5R5',
  'song_name': 'The Next Big Thing',
  'song_duration': 213880,
  'song_url': 'https://open.spotify.com/track/36GiaCkptseXOnP1SgG5R5',
  'song_added': '2017-05-20T13:39:55Z',
  'album_id': '2yuA6JcakppoD7xbiJmOix',
  'artist_id': '043r4OwwUAYREkBLK5jAiV'},
 {'song_id': '6M6ygXjmi1V4kekp5xxqOH',
  'song_name': 'Six Candles',
  'song_duration': 255053,
  'song_url': 'https://open.spotify.com/track/6M6ygXjmi1V4kekp5xxqOH',
  'song_added': '2017-05-20T13:39:59Z',
  'album_id': '2yuA6JcakppoD7xbiJmOix',
  'artist_id': '043r4OwwUAYREkBLK5jAiV'},
 {'song_id': '5nNTzExcnw0YbjCJPH6Hx8',
  'song_name': 'Nice Piece Of Art',
  'song_duration': 212573,
  'song_url': 'https://open.spotify.com/track/5nNTzExcnw0YbjCJPH6Hx8',
  'song_added': '2017-05-20T13:40:03Z',
  'album_id': '2yuA6JcakppoD7xbiJmOix',
  'artist_id': '043r4OwwUAYREkBLK5jAiV'},
 {'song_id': '5F2E79QbB4orWKa4VIXO2j',
  'song_name': 'Take Me As I Am',
  'song_duration': 212973,
  'song_url': 'https://open.spotify.com/track/5F2E79QbB4orWKa4VIXO2j',
  'song_added': '2017-05-20T13:40:07Z',
  'album_id': '5hQQ9xmWchSRYXNI6gJhz6',
  'artist_id': '043r4OwwUAYREkBLK5jAiV'},
 {'song_id': '37LNThlFJaNmi9SeLrv8H6',
  'song_name': 'Moment Of Truth',
  'song_duration': 226253,
  'song_url': 'https://open.spotify.com/track/37LNThlFJaNmi9SeLrv8H6',
  'song_added': '2017-05-20T13:40:11Z',
  'album_id': '2yuA6JcakppoD7xbiJmOix',
  'artist_id': '043r4OwwUAYREkBLK5jAiV'},
 {'song_id': '4BodkdQk2Ouo6BFbLqoWtG',
  'song_name': 'Tonight',
  'song_duration': 218586,
  'song_url': 'https://open.spotify.com/track/4BodkdQk2Ouo6BFbLqoWtG',
  'song_added': '2017-05-20T13:40:14Z',
  'album_id': '2yuA6JcakppoD7xbiJmOix',
  'artist_id': '043r4OwwUAYREkBLK5jAiV'},
 {'song_id': '44HdPuYShZtHgSqn7kssgT',
  'song_name': 'Damn Regret',
  'song_duration': 165976,
  'song_url': 'https://open.spotify.com/track/44HdPuYShZtHgSqn7kssgT',
  'song_added': '2017-05-20T13:40:30Z',
  'album_id': '6TyPSzd5rA2rQ9yLJJ1Gg2',
  'artist_id': '1SImpQO0GbjRgvlwCcCtFo'},
 {'song_id': '2Guz1b911CbpG8L92cnglI',
  'song_name': 'Your Guardian Angel',
  'song_duration': 229234,
  'song_url': 'https://open.spotify.com/track/2Guz1b911CbpG8L92cnglI',
  'song_added': '2017-05-20T13:40:35Z',
  'album_id': '6TyPSzd5rA2rQ9yLJJ1Gg2',
  'artist_id': '1SImpQO0GbjRgvlwCcCtFo'},
 {'song_id': '4wzjNqjKAKDU82e8uMhzmr',
  'song_name': 'Face Down',
  'song_duration': 192000,
  'song_url': 'https://open.spotify.com/track/4wzjNqjKAKDU82e8uMhzmr',
  'song_added': '2017-05-20T13:40:38Z',
  'album_id': '6TyPSzd5rA2rQ9yLJJ1Gg2',
  'artist_id': '1SImpQO0GbjRgvlwCcCtFo'},
 {'song_id': '6MqVzYyReYtY0Sgw9alj5I',
  'song_name': 'Say You Like Me',
  'song_duration': 210440,
  'song_url': 'https://open.spotify.com/track/6MqVzYyReYtY0Sgw9alj5I',
  'song_added': '2017-05-20T13:40:55Z',
  'album_id': '6WZXOQ3wVanWKocZND5qoZ',
  'artist_id': '3ao3jf5d70Tf4fPh2bnXVl'},
 {'song_id': '0wVluBsVAVzBKrqspuCcwR',
  'song_name': 'Check Yes, Juliet',
  'song_duration': 220146,
  'song_url': 'https://open.spotify.com/track/0wVluBsVAVzBKrqspuCcwR',
  'song_added': '2017-05-20T13:40:59Z',
  'album_id': '5kykHij9W4lQ4fFEfIo7BB',
  'artist_id': '3ao3jf5d70Tf4fPh2bnXVl'},
 {'song_id': '6OPoF9qiuV2dNfJ44w3X4M',
  'song_name': "Something's Gotta Give",
  'song_duration': 189418,
  'song_url': 'https://open.spotify.com/track/6OPoF9qiuV2dNfJ44w3X4M',
  'song_added': '2017-05-20T13:41:09Z',
  'album_id': '6SdmyV1DoEIWU6HDal5BgY',
  'artist_id': '46gyXjRIvN1NL1eCB8GBxo'},
 {'song_id': '0J69x3mqm7U6tBPKsjpsWR',
  'song_name': 'Dear Maria, Count Me In',
  'song_duration': 182826,
  'song_url': 'https://open.spotify.com/track/0J69x3mqm7U6tBPKsjpsWR',
  'song_added': '2017-05-20T13:41:12Z',
  'album_id': '7GcuimRczCCOblhJr0NgzD',
  'artist_id': '46gyXjRIvN1NL1eCB8GBxo'},
 {'song_id': '1NO4AeKW9dqRNp7qoo0Ono',
  'song_name': 'Her Love Is My Religion',
  'song_duration': 228052,
  'song_url': 'https://open.spotify.com/track/1NO4AeKW9dqRNp7qoo0Ono',
  'song_added': '2017-05-20T13:41:18Z',
  'album_id': '3bex1JTyWnMeQDX5kodWtc',
  'artist_id': '2C2sVVXanbOpymYBMpsi89'},
 {'song_id': '1TRrCyu9o8NYMPHR8G7dU0',
  'song_name': 'Temporary Bliss',
  'song_duration': 224932,
  'song_url': 'https://open.spotify.com/track/1TRrCyu9o8NYMPHR8G7dU0',
  'song_added': '2017-05-20T13:41:21Z',
  'album_id': '3bex1JTyWnMeQDX5kodWtc',
  'artist_id': '2C2sVVXanbOpymYBMpsi89'},
 {'song_id': '50XDQOyJSPUzh91BJAHKZA',
  'song_name': 'These Are The Lies',
  'song_duration': 226426,
  'song_url': 'https://open.spotify.com/track/50XDQOyJSPUzh91BJAHKZA',
  'song_added': '2017-05-20T13:41:25Z',
  'album_id': '0mtf5Q6b4CD0mx7UTtL0l1',
  'artist_id': '2C2sVVXanbOpymYBMpsi89'},
 {'song_id': '0V64VQHOOcwC60IMRrrXFa',
  'song_name': 'Endlessly',
  'song_duration': 237879,
  'song_url': 'https://open.spotify.com/track/0V64VQHOOcwC60IMRrrXFa',
  'song_added': '2017-05-20T13:41:31Z',
  'album_id': '3bex1JTyWnMeQDX5kodWtc',
  'artist_id': '2C2sVVXanbOpymYBMpsi89'},
 {'song_id': '3u8vWaQuAiXwIDUZLCbvJH',
  'song_name': 'Bad',
  'song_duration': 201506,
  'song_url': 'https://open.spotify.com/track/3u8vWaQuAiXwIDUZLCbvJH',
  'song_added': '2017-05-20T13:41:35Z',
  'album_id': '3bex1JTyWnMeQDX5kodWtc',
  'artist_id': '2C2sVVXanbOpymYBMpsi89'},
 {'song_id': '5A8jUZatix87xG0Zj6HSKG',
  'song_name': 'Angel With a Shotgun',
  'song_duration': 223092,
  'song_url': 'https://open.spotify.com/track/5A8jUZatix87xG0Zj6HSKG',
  'song_added': '2017-05-20T13:41:39Z',
  'album_id': '3bex1JTyWnMeQDX5kodWtc',
  'artist_id': '2C2sVVXanbOpymYBMpsi89'},
 {'song_id': '10rChmECwPcvTTj4w07hq4',
  'song_name': 'Welcome to My Life',
  'song_duration': 206773,
  'song_url': 'https://open.spotify.com/track/10rChmECwPcvTTj4w07hq4',
  'song_added': '2017-05-20T13:42:20Z',
  'album_id': '6RSpKXfvVzCqtLi6VySxsU',
  'artist_id': '2p4FqHnazRucYQHyDCdBrJ'},
 {'song_id': '2l7zQEMGWsPgQYtc2C5KtG',
  'song_name': "Nothing's Going To Change My Love For You",
  'song_duration': 227320,
  'song_url': 'https://open.spotify.com/track/2l7zQEMGWsPgQYtc2C5KtG',
  'song_added': '2017-05-20T13:42:31Z',
  'album_id': '1vD9N1kYJtYEBEzV1KZpH0',
  'artist_id': '5Z1CCuBsyhEHngq3U5IraY'},
 {'song_id': '5WlnivbFdzvk37socBY91p',
  'song_name': 'Queen of My Heart - Radio Edit',
  'song_duration': 257773,
  'song_url': 'https://open.spotify.com/track/5WlnivbFdzvk37socBY91p',
  'song_added': '2017-05-20T13:42:34Z',
  'album_id': '3Iq8rXgxwlSPpRsIacNLgK',
  'artist_id': '5Z1CCuBsyhEHngq3U5IraY'},
 {'song_id': '79h4aHx4xz2A77hXpHfflM',
  'song_name': 'I Can Wait Forever',
  'song_duration': 294320,
  'song_url': 'https://open.spotify.com/track/79h4aHx4xz2A77hXpHfflM',
  'song_added': '2017-05-20T13:42:42Z',
  'album_id': '1tjE6cuUdnscgwxTt49ouH',
  'artist_id': '2p4FqHnazRucYQHyDCdBrJ'},
 {'song_id': '3jzU2G7zznQ3bpUzNEBgmj',
  'song_name': 'Perfectly Perfect',
  'song_duration': 187186,
  'song_url': 'https://open.spotify.com/track/3jzU2G7zznQ3bpUzNEBgmj',
  'song_added': '2017-05-20T13:42:55Z',
  'album_id': '0cDtMoDHC3Pja0V1qrfBdT',
  'artist_id': '2p4FqHnazRucYQHyDCdBrJ'},
 {'song_id': '38z6jaLE0F13dxv28n3wlq',
  'song_name': 'Addicted',
  'song_duration': 232066,
  'song_url': 'https://open.spotify.com/track/38z6jaLE0F13dxv28n3wlq',
  'song_added': '2017-05-20T13:42:58Z',
  'album_id': '3rEl0zv6lbVZiB79uHAQ5y',
  'artist_id': '2p4FqHnazRucYQHyDCdBrJ'},
 {'song_id': '5uCax9HTNlzGybIStD3vDh',
  'song_name': "Say You Won't Let Go",
  'song_duration': 211477,
  'song_url': 'https://open.spotify.com/track/5uCax9HTNlzGybIStD3vDh',
  'song_added': '2017-05-20T13:43:04Z',
  'album_id': '7oiJYvEJHsmYtrgviAVIBD',
  'artist_id': '4IWBUUAFIplrNtaOHcJPRM'},
 {'song_id': '0jnNYYeMqMdreIsN22PzGk',
  'song_name': 'Afire Love',
  'song_duration': 314280,
  'song_url': 'https://open.spotify.com/track/0jnNYYeMqMdreIsN22PzGk',
  'song_added': '2017-05-20T13:43:40Z',
  'album_id': '0MeOIA0wwSa6nW79jy8QcZ',
  'artist_id': '6eUKZXaKkcviH0Ku9w2n3V'},
 {'song_id': '1mea3bSkSGXuIRvnydlB5b',
  'song_name': 'Viva La Vida',
  'song_duration': 242373,
  'song_url': 'https://open.spotify.com/track/1mea3bSkSGXuIRvnydlB5b',
  'song_added': '2017-05-20T13:44:09Z',
  'album_id': '1CEODgTmTwLyabvwd7HBty',
  'artist_id': '4gzpq5DPGxSnKTe4SA8HAU'},
 {'song_id': '5qfZRNjt2TkHEL12r3sDEU',
  'song_name': 'Everglow',
  'song_duration': 282693,
  'song_url': 'https://open.spotify.com/track/5qfZRNjt2TkHEL12r3sDEU',
  'song_added': '2017-05-20T13:44:13Z',
  'album_id': '3cfAM8b8KqJRoIzt3zLKqw',
  'artist_id': '4gzpq5DPGxSnKTe4SA8HAU'},
 {'song_id': '0FDzzruyVECATHXKHFs9eJ',
  'song_name': 'A Sky Full of Stars',
  'song_duration': 267866,
  'song_url': 'https://open.spotify.com/track/0FDzzruyVECATHXKHFs9eJ',
  'song_added': '2017-05-20T13:44:15Z',
  'album_id': '2G4AUqfwxcV1UdQjm2ouYr',
  'artist_id': '4gzpq5DPGxSnKTe4SA8HAU'},
 {'song_id': '75JFxkI2RXiU7L9VXzMkle',
  'song_name': 'The Scientist',
  'song_duration': 309600,
  'song_url': 'https://open.spotify.com/track/75JFxkI2RXiU7L9VXzMkle',
  'song_added': '2017-05-20T13:44:20Z',
  'album_id': '0RHX9XECH8IVI3LNgWDpmQ',
  'artist_id': '4gzpq5DPGxSnKTe4SA8HAU'},
 {'song_id': '1nRwyxNsqCLeA17qR8Nfxx',
  'song_name': 'Quit Playing Games (With My Heart)',
  'song_duration': 233533,
  'song_url': 'https://open.spotify.com/track/1nRwyxNsqCLeA17qR8Nfxx',
  'song_added': '2017-05-20T13:44:29Z',
  'album_id': '0wvQovgaVU99eqw8n3g22S',
  'artist_id': '5rSXSAkZ67PYJSvpUpkOr7'},
 {'song_id': '6e40mgJiCid5HRAGrbpGA6',
  'song_name': 'I Want It That Way',
  'song_duration': 213600,
  'song_url': 'https://open.spotify.com/track/6e40mgJiCid5HRAGrbpGA6',
  'song_added': '2017-05-20T13:44:35Z',
  'album_id': '1NslKOZobWxINFaFkLol3r',
  'artist_id': '5rSXSAkZ67PYJSvpUpkOr7'},
 {'song_id': '6vrUTGn5p8IrfTZ0J6sIVM',
  'song_name': 'Iris',
  'song_duration': 289906,
  'song_url': 'https://open.spotify.com/track/6vrUTGn5p8IrfTZ0J6sIVM',
  'song_added': '2017-05-20T13:44:45Z',
  'album_id': '0UccZZgelTAbbk3OSPZymO',
  'artist_id': '2sil8z5kiy4r76CRTXxBCA'},
 {'song_id': '0wqOReZDnrefefEsrIGeR4',
  'song_name': 'Hanging By A Moment',
  'song_duration': 216066,
  'song_url': 'https://open.spotify.com/track/0wqOReZDnrefefEsrIGeR4',
  'song_added': '2017-05-20T13:45:05Z',
  'album_id': '1VKNHcrUppE8i5oAhg4o6k',
  'artist_id': '5PokPZn11xzZXyXSfnvIM3'},
 {'song_id': '7L605WhF5EGf34ggj87yK6',
  'song_name': 'You And Me',
  'song_duration': 195493,
  'song_url': 'https://open.spotify.com/track/7L605WhF5EGf34ggj87yK6',
  'song_added': '2017-05-20T13:45:10Z',
  'album_id': '3wJfFDP79V0vuGaAasTIz6',
  'artist_id': '5PokPZn11xzZXyXSfnvIM3'},
 {'song_id': '4IoYz8XqqdowINzfRrFnhi',
  'song_name': 'You Found Me',
  'song_duration': 241853,
  'song_url': 'https://open.spotify.com/track/4IoYz8XqqdowINzfRrFnhi',
  'song_added': '2017-05-20T13:45:40Z',
  'album_id': '3ibdlhMmbFPMYoWvwHCzI3',
  'artist_id': '0zOcE3mg9nS6l3yxt1Y0bK'},
 {'song_id': '5fVZC9GiM4e8vu99W0Xf6J',
  'song_name': 'How to Save a Life',
  'song_duration': 262533,
  'song_url': 'https://open.spotify.com/track/5fVZC9GiM4e8vu99W0Xf6J',
  'song_added': '2017-05-20T13:45:43Z',
  'album_id': '1IM3GwptCGYjRkzCBolyFK',
  'artist_id': '0zOcE3mg9nS6l3yxt1Y0bK'},
 {'song_id': '4kbj5MwxO1bq9wjT5g9HaA',
  'song_name': 'Shut Up and Dance',
  'song_duration': 199080,
  'song_url': 'https://open.spotify.com/track/4kbj5MwxO1bq9wjT5g9HaA',
  'song_added': '2017-05-20T13:45:51Z',
  'album_id': '3mNoFlD1wsoXfkljfFzExT',
  'artist_id': '6DIS6PRrLS3wbnZsf7vYic'}]

In [38]:
album_df = pd.DataFrame.from_dict(album_list)
artist_df = pd.DataFrame.from_dict(artist_list)
song_df = pd.DataFrame.from_dict(song_list)

In [40]:
print(album_df.shape)
print(artist_df.shape)
print(song_df.shape)

(50, 5)
(50, 3)
(50, 7)

In [41]:
album_df.head()

,album_id,album_name,album_release_date,album_total_tracks,album_url
0,33XEF2uGTwEZuVmwXiK9d2,All That We Needed,2005-01-01,13,{'spotify': 'https://open.spotify.com/album/33...
1,7m7F7SQ3BXvIpvOgjW51Gp,Some Nights,2012-02-14,11,{'spotify': 'https://open.spotify.com/album/7m...
2,237sMnzUdsdO2GsINgnk2E,Can't Help Falling In Love,2016-02-12,1,{'spotify': 'https://open.spotify.com/album/23...
3,0ZQkueWQFxBrCsfkhxc4jg,Begin Again - Music From And Inspired By The O...,2014-07-01,16,{'spotify': 'https://open.spotify.com/album/0Z...
4,7oiJYvEJHsmYtrgviAVIBD,Back from the Edge,2016-10-28,17,{'spotify': 'https://open.spotify.com/album/7o...

In [42]:
artist_df.head()

,artist_id,artist_name,artist_url
0,1g1yxsNVPhMUl9GrMjEb2o,Plain White T's,{'spotify': 'https://open.spotify.com/artist/1...
1,5nCi3BB41mBaMH9gfr6Su0,fun.,{'spotify': 'https://open.spotify.com/artist/5...
2,40JlNF1w2OiSOyj1nC4y0I,Joseph Vincent,{'spotify': 'https://open.spotify.com/artist/4...
3,4bYPcJP5jwMhSivRcqie2n,Adam Levine,{'spotify': 'https://open.spotify.com/artist/4...
4,4IWBUUAFIplrNtaOHcJPRM,James Arthur,{'spotify': 'https://open.spotify.com/artist/4...

In [43]:
song_df.head()

,song_id,song_name,song_duration,song_url,song_added,album_id,artist_id
0,5O3eNPhckrOCxIBtR5SQLN,Hey There Delilah,232533,https://open.spotify.com/track/5O3eNPhckrOCxIB...,2017-05-20T13:37:28Z,33XEF2uGTwEZuVmwXiK9d2,1g1yxsNVPhMUl9GrMjEb2o
1,67WTwafOMgegV6ABnBQxcE,Some Nights,277040,https://open.spotify.com/track/67WTwafOMgegV6A...,2017-05-20T13:37:30Z,7m7F7SQ3BXvIpvOgjW51Gp,5nCi3BB41mBaMH9gfr6Su0
2,07ceQy7UhpNDA2WhEOJgPp,Can't Help Falling In Love,129434,https://open.spotify.com/track/07ceQy7UhpNDA2W...,2017-05-20T13:37:38Z,237sMnzUdsdO2GsINgnk2E,40JlNF1w2OiSOyj1nC4y0I
3,31UdITPwSCT5LcwbG29G3J,Lost Stars,267920,https://open.spotify.com/track/31UdITPwSCT5Lcw...,2017-05-20T13:37:48Z,0ZQkueWQFxBrCsfkhxc4jg,4bYPcJP5jwMhSivRcqie2n
4,0VhgEqMTNZwYL1ARDLLNCX,Can I Be Him,246775,https://open.spotify.com/track/0VhgEqMTNZwYL1A...,2017-05-20T13:37:52Z,7oiJYvEJHsmYtrgviAVIBD,4IWBUUAFIplrNtaOHcJPRM

In [44]:
# Remove duplicates

album_df = album_df.drop_duplicates(subset=['album_id'])
artist_df = artist_df.drop_duplicates(subset=['artist_id'])

In [47]:
album_df.info()

<class 'pandas.DataFrame'>
Index: 36 entries, 0 to 49
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   album_id            36 non-null     str
 1   album_name          36 non-null     str
 2   album_release_date  36 non-null     str
 3   album_total_tracks  36 non-null     int64
 4   album_url           36 non-null     object
dtypes: int64(1), object(1), str(3)
memory usage: 1.7+ KB

In [52]:
# Convert date columns

album_df['album_release_date'] = pd.to_datetime(
    album_df['album_release_date'],
    format='mixed',
    errors='coerce'
)

In [53]:
album_df.info()

<class 'pandas.DataFrame'>
Index: 36 entries, 0 to 49
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   album_id            36 non-null     str
 1   album_name          36 non-null     str
 2   album_release_date  36 non-null     datetime64[us]
 3   album_total_tracks  36 non-null     int64
 4   album_url           36 non-null     object
dtypes: datetime64[us](1), int64(1), object(1), str(2)
memory usage: 1.7+ KB

In [48]:
song_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   song_id        50 non-null     str
 1   song_name      50 non-null     str
 2   song_duration  50 non-null     int64
 3   song_url       50 non-null     str
 4   song_added     50 non-null     str
 5   album_id       50 non-null     str
 6   artist_id      50 non-null     str
dtypes: int64(1), str(6)
memory usage: 2.9 KB

In [49]:
# Convert date columns

song_df['song_added'] = pd.to_datetime(song_df['song_added'])

In [50]:
song_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   song_id        50 non-null     str
 1   song_name      50 non-null     str
 2   song_duration  50 non-null     int64
 3   song_url       50 non-null     str
 4   song_added     50 non-null     datetime64[us, UTC]
 5   album_id       50 non-null     str
 6   artist_id      50 non-null     str
dtypes: datetime64[us, UTC](1), int64(1), str(5)
memory usage: 2.9 KB